name: example
description: "Demonstrates how to use the flutter_custom_updater package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  flutter_custom_updater:
    path: ../

  cupertino_icons: ^1.0.8
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
