name: flutter_custom_updater
description: "Flutter package for internal app updates (APK & IPA). Ideal for self-hosted, enterprise, and private distribution."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

license: MIT

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  path_provider: ^2.1.1
  open_filex: ^4.3.4
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.1
  mockito: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
